services:
  mysql:
    image: mysql:8.0
    container_name: start-mysql-1
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql # использует том, а не локальную папку
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: my-site
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:latest
    depends_on:
      - mysql
    ports:
      - 8000:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: my-site
      WORDPRESS_DEBUG: 1
    volumes:
      - ./.srv/wordpress:/var/www/html
      - ./themes/:/var/www/html/wp-content/themes
      - ./plugins/:/var/www/html/wp-content/plugins
      - ./.srv/custom.ini:/usr/local/etc/php/conf.d/custom.ini

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_USERNAME: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
      PMA_HOST: mysql
    ports:
      - '8181:80'
    depends_on:
      - mysql
    links:
      - mysql

volumes:
  mysql_data: # Docker будет управлять этим томом автоматически
